Blogp22AspNetCore/Areas/Blog/Controllers/ArticleController.cs
using Blogp22AspNetCore.Areas.Blog.Models.Settings;
using Blogp22AspNetCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blogp22AspNetCore.Areas.Blog.Controllers
{
    public class ArticleController : Controller
    {

        private readonly BlogDBContext _context;
        private readonly IArticleRepository _articleRepository;

        public ArticleController(BlogDBContext context, IArticleRepository articleRepository)
        {
            _context = context;
            _articleRepository = articleRepository;
        }

        [HttpGet]
        //[Authorize]
		[Route("{area}/{controller}/{action}")]
		public async Task<ActionResult> Index()
        {
            var articles = await _articleRepository.GetAllArticlesAsync();
            return View(articles);
        }


		[HttpGet("{id}")]
		[Route("{area}/{controller}/{action}")]
		public async Task<ActionResult> Details(int id)
		{
			var article = await _articleRepository.GetArticleByIdAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            
            return View(article);
		}

        [HttpGet("{slug}")]
        [Route("{area}/{controller}/{action}")]
        public async Task<ActionResult> DetailsBySlug(string slug)
        {
            var article = await _articleRepository.GetArticleBySlugAsync(slug);
            if (article == null)
            {
                return NotFound();
            }

            return View("Details",article);
        }

        [Authorize]
        [HttpGet("create")]
        public IActionResult Create()
        {
            return View();
        }

    }
}

Blogp22AspNetCore/Areas/Blog/Views/Shared/_WithoutCarousel.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>NewsFeed | Pages | Single Page</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/bootstrap.min.css")"></link>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/font-awesome.min.css")"></link>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/animate.css")"></link>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/font.css")"></link>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/li-scroller.css")"></link>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/slick.css")"></link>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/jquery.fancybox.css")"></link>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/theme.css")"></link>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/assets/css/style.css")"></link>

</head>
<body>
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>
    <a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
    <div class="container">
        <header id="header">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="header_top">
                        <div class="header_top_left">
                            <ul class="top_nav">
                                <li><a asp-area="Blog" asp-controller="Home" asp-action="Index">Home</a></li>
                                <li><a asp-area="Blog" asp-controller="Article" asp-action="Index">Blog</a></li>
                                <li><a asp-area="Blog" asp-controller="Home" asp-action="Contact">Contact</a></li>
                            </ul>
                        </div>
                        <div class="header_top_right">
                            <p>@DateTime.Now</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="header_bottom">
                        <div class="logo_area"><a asp-controller="Home" asp-action="Index" class="logo"><img src="@Url.Content("~/images/logo.jpg")" alt=""></a></div>
                        <div class="add_banner"><a href="#"><img src="@Url.Content("~/images/addbanner_728x90_V1.jpg")" alt=""></a></div>
                    </div>
                </div>
            </div>
        </header>
        <section id="navArea">
            <nav class="navbar navbar-inverse" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav main_nav">
                        <li class="active"><a asp-controller="Home" asp-action="Index"><span class="fa fa-home desktop-home"></span><span class="mobile-show">Home</span></a></li>
                        <li><a href="#">Technology</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mobile</a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Android</a></li>
                                <li><a href="#">Samsung</a></li>
                                <li><a href="#">Nokia</a></li>
                                <li><a href="#">Walton Mobile</a></li>
                                <li><a href="#">Sympony</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Laptops</a></li>
                        <li><a href="#">Tablets</a></li>
                        <li><a asp-area="Blog" asp-controller="Home" asp-action="Contact">Contact Us</a></li>
                    </ul>
                </div>
            </nav>




        </section>
        <section id="newsSection">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="latest_newsarea">
                        <span>Latest News</span>
                        <ul id="ticker01" class="news_sticker">
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail3.jpg")" alt="">My First News Item</a></li>
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail3.jpg")" alt="">My Second News Item</a></li>
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail3.jpg")" alt="">My Third News Item</a></li>
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail3.jpg")" alt="">My Four News Item</a></li>
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail3.jpg")" alt="">My Five News Item</a></li>
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail3.jpg")" alt="">My Six News Item</a></li>
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail3.jpg")" alt="">My Seven News Item</a></li>
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail3.jpg")" alt="">My Eight News Item</a></li>
                            <li><a href="#"><img src="@Url.Content("~/images/news_thumbnail2.jpg")" alt="">My Nine News Item</a></li>
                        </ul>
                        <div class="social_area">
                            <ul class="social_nav">
                                <li class="facebook"><a href="#"></a></li>
                                <li class="twitter"><a href="#"></a></li>
                                <li class="flickr"><a href="#"></a></li>
                                <li class="pinterest"><a href="#"></a></li>
                                <li class="googleplus"><a href="#"></a></li>
                                <li class="vimeo"><a href="#"></a></li>
                                <li class="youtube"><a href="#"></a></li>
                                <li class="mail"><a href="#"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="contentSection">
            <div class="row">

                <div class="col-lg-8 col-md-8 col-sm-8">
                    <div class="left_content">
                        @RenderBody()
                    </div>
                </div>

                <nav class="nav-slit">
                    <a class="prev" href="#">
                        <span class="icon-wrap"><i class="fa fa-angle-left"></i></span>
                        <div>
                            <h3>City Lights</h3>
                            <img src="@Url.Content("~/images/post_img1.jpg")" alt="" />
                        </div>
                    </a> <a class="next" href="#">
                        <span class="icon-wrap"><i class="fa fa-angle-right"></i></span>
                        <div>
                            <h3>Street Hills</h3>
                            <img src="@Url.Content("~/images/post_img1.jpg")" alt="" />
                        </div>
                    </a>
                </nav>



                <div class="col-lg-4 col-md-4 col-sm-4">
                    <aside class="right_content">
                        <div class="single_sidebar">
                            <h2><span>Popular Post</span></h2>
                            <ul class="spost_nav">
                                <li>
                                    <div class="media wow fadeInDown">
                                        <a href="single_page.html" class="media-left"> <img alt="" src="@Url.Content("~/images/post_img1.jpg")"> </a>
                                        <div class="media-body"> <a href="single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 1</a> </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="media wow fadeInDown">
                                        <a href="single_page.html" class="media-left"> <img alt="" src="@Url.Content("~/images/post_img1.jpg")"> </a>
                                        <div class="media-body"> <a href="single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 2</a> </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="media wow fadeInDown">
                                        <a href="single_page.html" class="media-left"> <img alt="" src="@Url.Content("~/images/post_img1.jpg")"> </a>
                                        <div class="media-body"> <a href="single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 3</a> </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="media wow fadeInDown">
                                        <a href="single_page.html" class="media-left"> <img alt="" src="@Url.Content("~/images/post_img1.jpg")"> </a>
                                        <div class="media-body"> <a href="single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 4</a> </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </aside>
                </div>
            </div>
        </section>
        <footer id="footer">
            <div class="footer_top">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="footer_widget wow fadeInLeftBig">
                            <h2>Flickr Images</h2>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="footer_widget wow fadeInDown">
                            <h2>Tag</h2>
                            <ul class="tag_nav">
                                <li><a href="#">Games</a></li>
                                <li><a href="#">Sports</a></li>
                                <li><a href="#">Fashion</a></li>
                                <li><a href="#">Business</a></li>
                                <li><a href="#">Life &amp; Style</a></li>
                                <li><a href="#">Technology</a></li>
                                <li><a href="#">Photo</a></li>
                                <li><a href="#">Slider</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                        <div class="footer_widget wow fadeInRightBig">
                            <h2>Contact</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <address>
                                Perfect News,1238 S . 123 St.Suite 25 Town City 3333,USA Phone: 123-326-789 Fax: 123-546-567
                            </address>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer_bottom">
                <p class="copyright">Copyright &copy; 2045 <a href="../index.html">NewsFeed</a></p>
                <p class="developer">Developed By Wpfreeware</p>
            </div>
        </footer>
    </div>
    <script src="@Url.Content("/assets/js/jquery.min.js")"></script>
    <script src="@Url.Content("/assets/js/wow.min.js")"></script>
    <script src="@Url.Content("~/assets/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/assets/js/slick.min.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.li-scroller.1.0.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.newsTicker.min.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.fancybox.pack.js")"></script>
    <script src="@Url.Content("~/assets/js/custom.js")"></script>
</body>
</html>